server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: true
    nacos:
      server-addr: localhost:8848 # Nacos地址
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes: # 网关路由配置
        - id: driver-service # 路由1
          uri: lb://driver-service # 路由的目标地址
          predicates:
            - Path=/driver/**
        - id: supplier-service # 路由2
          uri: lb://supplier # 路由的目标地址
          predicates:
            - Path=/supplier/**
        - id: goods-service # 路由3
          uri: lb://goods/goods # 路由的目标地址
          predicates:
            - Path=/goods/** # 匹配路径为 /goods/goods
        - id: stock-service # 路由3
          uri: lb://stock/goods # 路由的目标地址
          predicates:
            - Path=/stock/** # 匹配路径为 /goods/goods